### ISSUE TITLE
repo_config of rpm_repository - broken config.repo

### ISSUE THREAD

**Issue by jano477** [pulp/squeezer#153]
Hi,

when using parameter `repo_config' as described in playbook-examples this leads to a 500 Internal Server Error from pulp when opening config.repo-file in a published and distributed rpm-repo.

I'm using latest dev-version of this module and the execution of the following ansible-tasks runs without any errors:

```
    - name: Create repository
      pulp.squeezer.rpm_repository:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        autopublish: "{{ item.autopublish }}"
        remote: "{{ item.remote_name }}"
        repo_config: 
          gpgcheck: 1
        state: present
      register: result
      tags:
        - create

    - name: Publish latest version of repository
      pulp.squeezer.rpm_publication:
        repository: "{{ item.name }}"
        state: present
      register: result
      tags:
        - create

    - name: Retrieve publication of repository
      pulp.squeezer.rpm_publication:
        repository: "{{ item.name }}"
      register: publication_result
      tags:
        - create

    - name: Distribute publication of repository
      pulp.squeezer.rpm_distribution:
        name: "{{item.name}}_distribution"
        base_path: "{{ item.name }}"
        publication: "{{ publication_result.publication.pulp_href }}"
        #content_guard: test_content_guard
        generate_repo_config: true
        state: present
      register: result
      tags:
        - create
```

The task for creating the rpm-repo and the tasks four publication/distribution are completed sucessfully:

```
TASK [Create repository] ***************************************************************************************************************************************************************************************************************************************************************

changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "autopublish": true,
            "description": "Upstream-Repo for MariaDB version 11.2",
            "name": "upstream_mariadb-11.2",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "pulp_url": "https://pulp-test.domain.de",
            "refresh_api_cache": false,
            "remote": "mariadb-11.2",
            "repo_config": "{\"gpgcheck\": 1}",
            "state": "present",
            "username": "admin",
            "validate_certs": true
        }
    },
    "repository": {
        "autopublish": true,
        "checksum_type": null,
        "compression_type": null,
        "description": "Upstream-Repo for MariaDB version 11.2",
        "gpgcheck": null,
        "latest_version_href": "/pulp/api/v3/repositories/rpm/rpm/018e75e3-2f9c-7f1e-ac5d-21f4055962b3/versions/0/",
        "metadata_checksum_type": null,
        "metadata_signing_service": null,
        "name": "upstream_mariadb-11.2",
        "package_checksum_type": null,
        "pulp_created": "2024-03-25T13:53:26.941435Z",
        "pulp_href": "/pulp/api/v3/repositories/rpm/rpm/018e75e3-2f9c-7f1e-ac5d-21f4055962b3/",
        "pulp_labels": {},
        "pulp_last_updated": "2024-03-25T13:53:26.949720Z",
        "remote": "/pulp/api/v3/remotes/rpm/rpm/018e75e3-2409-7e0f-9883-61683f6fd3f0/",
        "repo_config": "{\"gpgcheck\": 1}",
        "repo_gpgcheck": null,
        "retain_package_versions": 0,
        "retain_repo_versions": null,
        "sqlite_metadata": false,
        "versions_href": "/pulp/api/v3/repositories/rpm/rpm/018e75e3-2f9c-7f1e-ac5d-21f4055962b3/versions/"
    }
}
```

Afterwards I browse through the new repo via pulp-webserver and there is a config.repo file with no size or date. If I try to open it, it leads to a 500.

![image](https://github.com/pulp/squeezer/assets/126000720/3cc9b5fb-2a44-41cd-883d-461e52e2679a)
![image](https://github.com/pulp/squeezer/assets/126000720/07d2a35c-7df7-4c03-9e2a-1956d132c3cf)

The log of pulpcore-content contains the followting when opening the config.repo-file:
```
Mar 25 15:26:42 gee6.domain.de pulpcore-content[343549]: AttributeError: 'str' object has no attribute 'pop'
Mar 25 15:26:42 gee6.domain.de pulpcore-content[343549]: ::ffff:127.0.0.1 [25/Mar/2024:14:26:42 +0000] "GET /pulp/content/upstream_mariadb-11.2/config.repo HTTP/1.0" 500 315 "https://pulp-test.domain.de/pulp/content/upstream_mariadb-11.2/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
```

I also tried the JSON-notation of repo_config which lead to the same result. 

The answer of the pulp-API endpoint for rpm-repositories shows the following:
```
"results": [
        {
            "pulp_href": "/pulp/api/v3/repositories/rpm/rpm/018e75e3-2f9c-7f1e-ac5d-21f4055962b3/",
            "pulp_created": "2024-03-25T13:53:26.941435Z",
            "pulp_last_updated": "2024-03-25T13:53:34.044634Z",
            "versions_href": "/pulp/api/v3/repositories/rpm/rpm/018e75e3-2f9c-7f1e-ac5d-21f4055962b3/versions/",
            "pulp_labels": {},
            "latest_version_href": "/pulp/api/v3/repositories/rpm/rpm/018e75e3-2f9c-7f1e-ac5d-21f4055962b3/versions/1/",
            "name": "upstream_mariadb-11.2",
            "description": "Upstream-Repo for MariaDB version 11.2",
            "retain_repo_versions": null,
            "remote": "/pulp/api/v3/remotes/rpm/rpm/018e75e3-2409-7e0f-9883-61683f6fd3f0/",
            "autopublish": true,
            "metadata_signing_service": null,
            "retain_package_versions": 0,
            "checksum_type": null,
            "metadata_checksum_type": null,
            "package_checksum_type": null,
            "gpgcheck": null,
            "repo_gpgcheck": null,
            "sqlite_metadata": false,
            "repo_config": "{\"gpgcheck\": 1}",
            "compression_type": null
        }
]
```

When I leave out the repo_config parameter the config,repo-file is created and readable.
