### ISSUE TITLE
deb_remote distributions problem

### ISSUE THREAD

**Issue by balleman** [pulp/squeezer#195]
Starting in version 0.1.0, it appears the deb_remote distribution property is being mishandled resulting in a new space added after every character, causing the remote sync to fail:

> TASK [pulp-repos : Debug Remote] *****************************************************************************************************
ok: [pulp] => {
    "remote": {
        "changed": true,
        "diff": {
            "after": {
                "architectures": "amd64",
                "ca_cert": null,
                "client_cert": null,
                "components": "main restricted universe multiverse",
                "connect_timeout": null,
                "distributions": "j a m m y   j a m m y - u p d a t e s   j a m m y - b a c k p o r t s",
> ...

We're providing distributions as a space-separated string, but changing to a list did not work either.

Our workaround has been to return to v0.0.20.  

This is with ansible version:
> ansible-playbook [core 2.17.10]
> python version = 3.11.2 (main, Nov 30 2024, 21:22:50) [GCC 12.2.0] (/usr/bin/python3)
> jinja version = 3.1.2

**Comment by mdellweg** [comment]
Can you take a look at this test where it seems to work as expected?
https://github.com/pulp/squeezer/blob/develop/tests/playbooks/deb_remote.yaml#L33

What is the difference here?

**Comment by uncycler** [comment]
I have the same issue if components or distributions is > 1:
```
"components": "m a i n   r e s t r i c t e d",
```

**Comment by mdellweg** [comment]
@balleman @uncycler Can you have a look at #210 and tell me if this improved test is still missing something? I'd like to close this issue.

**Comment by h3krn** [comment]
Hi @mdellweg,
Appologies for commenting on a closed issue. I'm running into this scenario with pulp_squeezer 0.4.0
One thing I did not read in the original problem is that this only happens when modifying an existing remote. 

Create a remote like with
```
---
- name: Create repos
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Set pulp.squeezer environment
      environment:
        - SQUEEZER_PULP_URL: http://localhost
        - SQUEEZER_USERNAME: admin
        - SQUEEZER_PASSWORD: "{{ packagerepo_pulp_admin_password }}"
      block:
        - name: "Create deb remote"
          pulp.squeezer.deb_remote:
            name: debian
            url: http://ftp.nl.debian.org/debian/
            architectures: amd64
            components: main
            distributions: trixie
            state: present
```
This results in a valid remote
```
# pulp deb remote show --name debian
{
  "pulp_href": "/pulp/api/v3/remotes/deb/apt/019eef68-6683-70a3-86dc-fcd54a6818e4/",
  "prn": "prn:deb.aptremote:019eef68-6683-70a3-86dc-fcd54a6818e4",
  "pulp_created": "2026-06-22T12:57:37.155766Z",
  "pulp_last_updated": "2026-06-22T12:57:37.155780Z",
  "name": "debian",
  "url": "http://ftp.nl.debian.org/debian/",
  "pulp_labels": {},
  "policy": "immediate",
  "hidden_fields": [
    {
      "name": "client_key",
      "is_set": false
    },
    {
      "name": "proxy_username",
      "is_set": false
    },
    {
      "name": "proxy_password",
      "is_set": false
    },
    {
      "name": "username",
      "is_set": false
    },
    {
      "name": "password",
      "is_set": false
    }
  ],
  "ca_cert": null,
  "client_cert": null,
  "tls_validation": true,
  "proxy_url": null,
  "max_retries": null,
  "total_timeout": null,
  "connect_timeout": null,
  "sock_connect_timeout": null,
  "sock_read_timeout": null,
  "headers": null,
  "download_concurrency": null,
  "rate_limit": null,
  "distributions": "trixie",
  "components": "main",
  "architectures": "amd64",
  "sync_sources": false,
  "sync_udebs": false,
  "sync_installer": false,
  "gpgkey": null,
  "ignore_missing_package_indices": false
}
```
Updating the existing remote (e.g. adding or modifing a component, distro or architecture) then breaks it.
```
--
- name: Create repos
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Set pulp.squeezer environment
      environment:
        - SQUEEZER_PULP_URL: http://localhost
        - SQUEEZER_USERNAME: admin
        - SQUEEZER_PASSWORD: "{{ packagerepo_pulp_admin_password }}"
      block:
        - name: "Create deb remote"
          pulp.squeezer.deb_remote:
            name: debian
            url: http://ftp.nl.debian.org/debian/
            architectures:
              - amd64
              - arm64
            components: main
            distributions: trixie
            state: present
```
Results in:
```
# pulp deb remote show --name debian
{
  "pulp_href": "/pulp/api/v3/remotes/deb/apt/019eef68-6683-70a3-86dc-fcd54a6818e4/",
  "prn": "prn:deb.aptremote:019eef68-6683-70a3-86dc-fcd54a6818e4",
  "pulp_created": "2026-06-22T12:57:37.155766Z",
  "pulp_last_updated": "2026-06-22T12:58:10.751411Z",
  "name": "debian",
  "url": "http://ftp.nl.debian.org/debian/",
  "pulp_labels": {},
  "policy": "immediate",
  "hidden_fields": [
    {
      "name": "client_key",
      "is_set": false
    },
    {
      "name": "proxy_username",
      "is_set": false
    },
    {
      "name": "proxy_password",
      "is_set": false
    },
    {
      "name": "username",
      "is_set": false
    },
    {
      "name": "password",
      "is_set": false
    }
  ],
  "ca_cert": null,
  "client_cert": null,
  "tls_validation": true,
  "proxy_url": null,
  "max_retries": null,
  "total_timeout": null,
  "connect_timeout": null,
  "sock_connect_timeout": null,
  "sock_read_timeout": null,
  "headers": null,
  "download_concurrency": null,
  "rate_limit": null,
  "distributions": "trixie",
  "components": "main",
  "architectures": "a m d 6 4   a r m 6 4",
  "sync_sources": false,
  "sync_udebs": false,
  "sync_installer": false,
  "gpgkey": null,
  "ignore_missing_package_indices": false
}
```

Ansible on my controller
```
$ ansible --version
ansible [core 2.16.3]
  config file = None
  configured module search path = ['/home/harm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/harm/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Mar 23 2026, 19:04:32) [GCC 13.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

Pip libs installed on my pulp host
```
# pip list | grep pulp
pulp-cli             0.33.2
pulp-cli-deb         0.3.5
pulp-glue            0.33.2
pulp-glue-deb        0.3.5
```
