### ISSUE TITLE
No idempotency for publications when multiple exist

### ISSUE THREAD

**Issue by markgoddard** [pulp/squeezer#84]
# Steps to reproduce

Create multiple publications for a single repository version.

```
pulp rpm publication create --repository foo
pulp rpm publication create --repository foo
```

Use the rpm_publication module to define the same publication:

```
- name: Ensure RPM publications are defined
  pulp.squeezer.rpm_publication:
    <credential params>
    repository: foo
    state: present
```

# Expected

No new publication is created.

# Actual

A new, third publication is created.

# Analysis

This happens due to the find() method on PulpEntity looking for count==1. It uses a limit of one, so only one result is returned, but the count still gives the full number of matching items, which in this case is 2.
